/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DogrulamaRouteImport } from './routes/dogrulama'

const DogrulamaRoute = DogrulamaRouteImport.update({
  id: '/dogrulama',
  path: '/dogrulama',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dogrulama': typeof DogrulamaRoute
}
export interface FileRoutesByTo {
  '/dogrulama': typeof DogrulamaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dogrulama': typeof DogrulamaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dogrulama'
  fileRoutesByTo: FileRoutesByTo
  to: '/dogrulama'
  id: '__root__' | '/dogrulama'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DogrulamaRoute: typeof DogrulamaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dogrulama': {
      id: '/dogrulama'
      path: '/dogrulama'
      fullPath: '/dogrulama'
      preLoaderRoute: typeof DogrulamaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DogrulamaRoute: DogrulamaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
